/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DictionaryPackage;

import javax.swing.JOptionPane;

/**
 *
 * @author Matt Andrei Belano
 */
public class DICTIONARYPAGE extends javax.swing.JFrame {

    /**
     * Creates new form DICTIONARYPAGE
     */
    public DICTIONARYPAGE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        pr = new javax.swing.JProgressBar();
        jLabel11 = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        pt = new javax.swing.JTextField();
        textField1 = new java.awt.TextField();
        jFrame1 = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        mm = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        nn = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        mn = new javax.swing.JEditorPane();
        mmm = new javax.swing.JToggleButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        mnm = new javax.swing.JEditorPane();
        tt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        txttt = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        jPanel1.setMaximumSize(new java.awt.Dimension(960, 625));
        jPanel1.setLayout(null);

        jLabel7.setText("jLabel7");

        jLabel8.setText("jLabel8");

        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel11.setText("jLabel11");

        jFormattedTextField2.setText("jFormattedTextField2");

        textField1.setText("textField1");
        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        mm.setColumns(20);
        mm.setRows(5);
        jScrollPane2.setViewportView(mm);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jScrollPane3.setViewportView(mn);

        mmm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmmActionPerformed(evt);
            }
        });

        jScrollPane5.setViewportView(mnm);

        tt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel12.setText("jLabel12");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel13.setText("jLabel13");

        jLabel14.setText("jLabel14");
        jLabel14.setMaximumSize(new java.awt.Dimension(900, 600));

        jLabel16.setText("jLabel16");

        jLabel15.setText("jLabel15");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(DICTIONARYPAGE.DO_NOTHING_ON_CLOSE);
        setTitle("DICTIONARY PAGE");
        setMaximumSize(new java.awt.Dimension(600, 500));
        setResizable(false);

        jPanel2.setMaximumSize(new java.awt.Dimension(500, 300));
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 521));
        jPanel2.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("DICTIONARY");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(80, 0, 270, 70);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Enter a keywords");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(50, 90, 110, 20);

        txt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtActionPerformed(evt);
            }
        });
        jPanel2.add(txt);
        txt.setBounds(50, 110, 220, 30);

        jButton1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton1.setText("Search");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(270, 110, 90, 30);

        jButton2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButton2.setText("Log out");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(160, 290, 110, 40);

        txttt.setEditable(false);
        txttt.setColumns(20);
        txttt.setLineWrap(true);
        txttt.setRows(5);
        txttt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jScrollPane6.setViewportView(txttt);

        jPanel2.add(jScrollPane6);
        jScrollPane6.setBounds(50, 170, 320, 100);

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\Important files\\Java bg\\stack-of-colorful-books.jpg")); // NOI18N
        jLabel17.setText("jLabel17");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(0, 0, 420, 350);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      
      if (txt.getText().equals("")){
       JOptionPane.showMessageDialog(null,"Please enter a keywords","Message",JOptionPane.ERROR_MESSAGE);
       }
      else if(txt.getText().equals("Abstruse")){
      txttt.setText("difficult to understand; obscure");
       }
      else if(txt.getText().equals("Bombastic")){
      txttt.setText("high-sounding but with little meaning; inflated");
       }
      else if(txt.getText().equals("Cacophony")){
      txttt.setText("a harsh, discordant mixture of sounds");
       }
      else if(txt.getText().equals("Disparate")){
      txttt.setText("essentially different in kind; not allowing comparison");
       }
      else if(txt.getText().equals("Ebullient")){
      txttt.setText("cheerful and full of energy");
       }
      else if(txt.getText().equals("Fastidious")){
      txttt.setText("very attentive to and concerned about accuracy and detail");
       }
      else if(txt.getText().equals("Grandiloquen")){
      txttt.setText("pompous or extravagant in language, style, or manner, especially in a way that is intended to impress");
       }
      else if(txt.getText().equals("Harangue")){
      txttt.setText("a lengthy and aggressive speech");
       }
      else if(txt.getText().equals("Ineffable")){
      txttt.setText("too great or extreme to be expressed or described in words");
       }
      else if(txt.getText().equals("Juxtapose")){
      txttt.setText("to place or deal with close together for contrasting effect");
       }
      else if(txt.getText().equals("Kowtow")){
      txttt.setText("to act in an excessively subservient manner");
       }
      else if(txt.getText().equals("Mellifluous")){
      txttt.setText("sweet or musical; pleasant to hear");
       }
      else if(txt.getText().equals("Nefarious")){
      txttt.setText("(typically of an action or activity) wicked, villainous, or criminal");
       }
      else if(txt.getText().equals("Obfuscate")){
      txttt.setText("to deliberately make something unclear or difficult to understand");
       }
      else if(txt.getText().equals("Perspicacious")){
      txttt.setText("having a ready insight into and understanding of things");
       }  
        else if(txt.getText().equals("Quixotic")){
      txttt.setText("extremely idealistic, unrealistic, and impractical");
       }
      else if(txt.getText().equals("Reticent")){
      txttt.setText("reserved or reluctant to speak");
       }
      else if(txt.getText().equals("Sycophant")){
      txttt.setText(" a person who acts obsequiously towards someone important to gain advantage");
       }
      else if(txt.getText().equals("Truculent")){
      txttt.setText("eager or quick to argue or fight; aggressively defiant");
       }
      else if(txt.getText().equals("Ubiquitous")){
      txttt.setText("present, appearing, or found everywhere");
       }
      else if(txt.getText().equals("Vexatious")){
      txttt.setText("causing annoyance, frustration, or worry");
       }
      else if(txt.getText().equals("Winsome")){
      txttt.setText("attractive or appealing in appearance or character");
       }
      else if(txt.getText().equals("Xenophobe")){
      txttt.setText("a person who dislikes or is prejudiced against people from other countries");
       }
      else if(txt.getText().equals("Yokel")){
      txttt.setText("an uneducated and unsophisticated person from the countryside");
       }
      else if(txt.getText().equals("Zephyr")){
      txttt.setText("a gentle, mild breeze");
       }
      else if(txt.getText().equals("Abyssal")){
      txttt.setText("relating to the depths of the ocean, especially below 2,000 meters (6,600 feet)");
       }
      else if(txt.getText().equals("Bellicose")){
      txttt.setText("demonstrating aggression and willingness to fight");
       }
      else if(txt.getText().equals("Chicanery")){
      txttt.setText("the use of trickery to achieve a political, financial, or legal purpose");
       }
      else if(txt.getText().equals("Diaphanous")){
      txttt.setText(" light, delicate, and translucent");
      }
      else if(txt.getText().equals("Esoteric")){
      txttt.setText("intended for or likely to be understood by only a small number of people with special knowledge");  
      }  
      else if(txt.getText().equals("Facetious")){
      txttt.setText("treating serious issues with inappropriate humor");
       }
      else if(txt.getText().equals("Garrulous")){
      txttt.setText("excessively talkative, especially about trivial matters");
       }
      else if(txt.getText().equals("Ineffable")){
      txttt.setText("too great or extreme to be expressed or described in words");
       }
      else if(txt.getText().equals("Juxtapose")){
      txttt.setText("to place or deal with close together for contrasting effect");
      }
      else if(txt.getText().equals("Kindle")){
      txttt.setText("to ignite or inspire");  
      }      
      else if(txt.getText().equals("Lethargic")){
      txttt.setText("affected by a lack of energy or enthusiasm");  
      }   
      else if(txt.getText().equals("Meticulous")){
      txttt.setText("showing great attention to detail; very careful and precise");  
      }   
      else if(txt.getText().equals("Nebulous")){
      txttt.setText("unclear, hazy, or vague");  
      }   
      else if(txt.getText().equals("Obfuscate")){
      txttt.setText("to deliberately make something unclear or difficult to understand");  
      }   
      else if(txt.getText().equals("Pernicious")){
      txttt.setText("having a harmful effect, especially in a gradual or subtle way");  
      }   
      else if(txt.getText().equals("Reticent")){
      txttt.setText("eserved or reluctant to speak");  
      }   
      else if(txt.getText().equals("Trepidation")){
      txttt.setText(" a feeling of fear or agitation about something that may happen");  
      }   
      else if(txt.getText().equals("Vacillate")){
      txttt.setText("to waver between different opinions or actions");  
      }   
      else if(txt.getText().equals("Wry ")){
      txttt.setText("using or expressing dry, especially mocking, humor");  
      }   
      else if(txt.getText().equals("Zenith")){
      txttt.setText("the highest point reached in the heavens or in a person's career");  
      }   
      else if(txt.getText().equals("Lugubrious")){
      txttt.setText("looking or sounding sad and dismal");  
      }   
      else if(txt.getText().equals("Pulchritudinous")){
      txttt.setText("Beautiful or physically attractive.");  
      }   
      else if(txt.getText().equals("Sesquipedalian")){
      txttt.setText("Characterized by long words; tending to use long words.");  
      }   
     else if(txt.getText().equals("Perspicacious")){
      txttt.setText("Having a keen sense of perception, insight, or understanding.");  
      }  
      else {
      JOptionPane.showMessageDialog(null,"Invalid keywords","Message",JOptionPane.ERROR_MESSAGE);
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtActionPerformed
        // TODO add your handling code here:
  
    }//GEN-LAST:event_txtActionPerformed

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    private void mmmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mmmActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        LoginForm lf = new LoginForm();
        lf.setVisible(true);
        lf.pack();
        lf.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DICTIONARYPAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DICTIONARYPAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DICTIONARYPAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DICTIONARYPAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DICTIONARYPAGE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextArea mm;
    private javax.swing.JToggleButton mmm;
    private javax.swing.JEditorPane mn;
    private javax.swing.JEditorPane mnm;
    private javax.swing.JLabel nn;
    private javax.swing.JProgressBar pr;
    private javax.swing.JTextField pt;
    private java.awt.TextField textField1;
    private javax.swing.JTextField tt;
    private javax.swing.JTextField txt;
    private javax.swing.JTextArea txttt;
    // End of variables declaration//GEN-END:variables
}
