/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DictionaryPackage;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Matt Andrei Belano
 */
public class Signup extends javax.swing.JFrame {
      
    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fnamedb = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        emm = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        userdb = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        passdb = new javax.swing.JPasswordField();
        ck = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        emlab = new javax.swing.JLabel();
        emlab1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jTree1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jCheckBox1.setText("jCheckBox1");

        jLabel5.setText("jLabel5");

        jButton1.setText("jButton1");

        jLabel8.setText("jLabel8");

        jLabel9.setText("jLabel9");

        jLabel10.setText("jLabel10");
        jLabel10.setMaximumSize(new java.awt.Dimension(847, 700));

        jLabel11.setText("jLabel11");

        jLabel12.setText("jLabel12");

        jLabel13.setText("jLabel13");

        jLabel6.setText("jLabel6");

        jLabel17.setText("jLabel17");

        jLabel18.setText("jLabel18");

        jLabel14.setText("jLabel14");

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\Important files\\Java bg\\book-863418_1280 - Copy (3).jpg")); // NOI18N
        jLabel15.setText("jLabel15");

        jLabel16.setText("jLabel16");

        setDefaultCloseOperation(Signup.DO_NOTHING_ON_CLOSE);
        setTitle("SIGN UP FORM");
        setMaximumSize(new java.awt.Dimension(450, 370));
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(800, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 470));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("FULLNAME");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 110, 70, 14);

        fnamedb.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        fnamedb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnamedbActionPerformed(evt);
            }
        });
        jPanel1.add(fnamedb);
        fnamedb.setBounds(130, 100, 207, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("EMAIL");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 160, 85, 14);

        emm.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel1.add(emm);
        emm.setBounds(130, 150, 207, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("USERNAME");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 210, 72, 14);

        userdb.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        userdb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userdbActionPerformed(evt);
            }
        });
        jPanel1.add(userdb);
        userdb.setBounds(130, 200, 207, 32);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("PASSWORD");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 260, 70, 14);

        passdb.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        passdb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passdbActionPerformed(evt);
            }
        });
        jPanel1.add(passdb);
        passdb.setBounds(130, 250, 207, 30);

        ck.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ck.setForeground(new java.awt.Color(0, 0, 0));
        ck.setText("Show password");
        ck.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        ck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckActionPerformed(evt);
            }
        });
        jPanel1.add(ck);
        ck.setBounds(130, 280, 131, 20);

        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setText("CREATE");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(230, 360, 110, 40);

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("CREATE ACCOUNT");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(70, 10, 260, 72);

        emlab.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        emlab.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(emlab);
        emlab.setBounds(230, 200, 210, 0);

        emlab1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(emlab1);
        emlab1.setBounds(240, 200, 200, 0);

        jButton3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton3.setText("Cancel");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(50, 360, 100, 40);

        jLabel19.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\Important files\\Java bg\\stack-of-colorful-books.jpg")); // NOI18N
        jLabel19.setText("jLabel19");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(0, 0, 390, 408);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userdbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userdbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userdbActionPerformed

    private void ckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckActionPerformed
        // TODO add your handling code here:
        
       if (ck.isSelected()) {
       passdb.setEchoChar((char)0);
     
       }
       else { 
       passdb.setEchoChar('*');
       
       }
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_ckActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
  
   
   
       String Fullname = fnamedb.getText();
       String Email = emm.getText();
       String Username= userdb.getText();
       String Password = passdb.getText();
         
        String url = "jdbc:mysql://localhost:3306/dcdatabase";
        String username = "root";
        String password = "";
    
  try {  
        Class.forName("com.mysql.cj.jdbc.Driver");
           Connection conn = DriverManager.getConnection(url, username, password);
           
      if (conn != null){
      if (fnamedb.getText().equals("")){
              JOptionPane.showMessageDialog(null, "Please enter fullname","Error ", JOptionPane.ERROR_MESSAGE);
                   }
      else if (emm.getText().equals("")){
                   JOptionPane.showMessageDialog(null, "Please enter email", "Error ", JOptionPane.ERROR_MESSAGE);
                        } 
      else if(userdb.getText().equals("")){
                        JOptionPane.showMessageDialog(null, "Please enter username", "Error ", JOptionPane.ERROR_MESSAGE);
                             }
      else if(passdb.getText().equals("")){
                             JOptionPane.showMessageDialog(null, "Please enter password", "Error ", JOptionPane.ERROR_MESSAGE);
                                   }
      else { 
        Statement stmt = conn.createStatement();
           String insert = "INSERT INTO dbdictionary(Fullname,Email,Username,Password) VALUES ('"+Fullname+"','"+Email+"','"+Username+"','"+Password+"')";
              stmt.execute(insert);
  
            
       LoginForm lf = new LoginForm();
          lf.setVisible(true);
             lf.pack();
               lf.setLocationRelativeTo(null);
                   this.dispose();
               }
          }
     }
     catch (SQLException ex){
     ex.printStackTrace();
     }  catch (ClassNotFoundException ex) {   
            Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
        }   
        
        
        
        
        
    
            
    }//GEN-LAST:event_jButton2ActionPerformed

    private void passdbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passdbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passdbActionPerformed

    private void fnamedbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnamedbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnamedbActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        LoginForm pr = new  LoginForm();
        pr.setVisible(true);
        pr.pack();
        pr.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ck;
    private javax.swing.JLabel emlab;
    private javax.swing.JLabel emlab1;
    private javax.swing.JTextField emm;
    private javax.swing.JTextField fnamedb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTree jTree1;
    private javax.swing.JPasswordField passdb;
    private javax.swing.JTextField userdb;
    // End of variables declaration//GEN-END:variables
}
